# mongodb-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-rolebinding
subjects:
- kind: ServiceAccount
  name: mongodb-sa
roleRef:
  kind: Role
  name: mongodb-role
  apiGroup: rbac.authorization.k8s.io