apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: us-east-1
  version: "1.21"

vpc:
  subnets:
    public:
      us-east-1a: 
        id: "subnet-03c1e3efc05a20333"
      us-east-1b: 
        id: "subnet-0a1698f89d640a509"
      us-east-1c: 
        id: "	subnet-07cf5fe3323d2975e"