apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: example-job
            image: busybox
            command: ["sh", "-c", "date; echo Hello from the CronJob"]
          restartPolicy: OnFailure
