apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel
  namespace: cafe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel
  template:
    metadata:
      labels:
        app: hotel
    spec:
      volumes:
      - name: hotel-volume
        persistentVolumeClaim:
          claimName: hotel-pv-claim

      containers:
      - name: coffee
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
        volumeMounts:
          - name: hotel-volume
            mountPath: "/var/persistent"

      containers:
      - name: tea
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80