apiVersion: v1
kind: PersistentVolume
metadata:
  name: hotel-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: hotelstorage
  mountOptions:
    - nfsvers=4.1
  nfs:
    path: /nfsdata
    server: <ip-address>