apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel
  namespace: cafe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel
  template:
    metadata:
      labels:
        app: hotel
    spec:
      volumes:
      - name: volume1
        hostPath:
          path: /mnt/data1
      - name: volume2
        hostPath:
          path: /mnt/data2

      containers:
      - name: coffee
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
        volumeMounts:
          - name: volume1
            mountPath: "/var/coffee"

      containers:
      - name: tea
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
        volumeMounts:
          - name: volume2
            mountPath: "/var/tea"